# File: .github/workflows/build-and-push.yml

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    # Specify your self-hosted runner's labels
    runs-on: [self-hosted, linux, docker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install hpccm
        run: |
          python -m pip install --upgrade pip
          pip install hpccm

      - name: Generate Dockerfile
        run: hpccm --format singularity --recipe ogbon_recipe.py > Dockerfile

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          TAG=${{ github.sha }}

          docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          TAG=${{ github.sha }}

          docker push $IMAGE_NAME:$TAG

