# File: .github/workflows/build-and-push.yml
name: Build and Push Docker Image
# Trigger the workflow on push to the main branch or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need
      # Step 3: Install hpccm
      - name: Install hpccm
        run: |
          python -m pip install --upgrade pip
          pip install hpccm
      # Step 4: Generate Dockerfile using hpccm
      - name: Generate Dockerfile
        run: hpccm --format docker --recipe ogbon_recipe.py > Dockerfile
      # Step 5: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }}
      # Step 6: Build the Docker image
      - name: Build Docker image
        run: |
          # Define image name and tag
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          TAG=latest  # You can modify the tag as needed, e.g., based on commit SHA
          # Build the Docker image
          docker build -t $IMAGE_NAME:$TAG .
      # Step 7: Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
          TAG=latest
          # Push the Docker image
          docker push $IMAGE_NAME:$TAG

